Camera zoom
TheAliceProject/alice3 pull request #318
Opened 2023-04-28 20:39 UTC by jennej

new one shot action for centering instead of on selection changes

slightly improved math for the ortho camera layout

some code cleanup

2023-05-01 17:05 UTC, dabeshouse requested changes
Fewer // pass!
Thank you!
A question about DEFAULT_LAYOUT_CAMERA_Y_OFFSET.
A few checkstyle compliance requests. 
A few comments to ignore.

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/sceneeditor/StorytellingSceneEditor.java
> +        // Turn markers on, so they're visible in the scene editor (note: markers are hidden by default so that when a world runs they aren't seen.
I si what you did there

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/croquet/models/ast/CenterCameraOnOperation.java
> +    private static Map<UserField, CenterCameraOnOperation> map = Maps.newHashMap();
Another static map makes me sad.
Yes, using a static map is how many Operations work.
And yes, this one is not as likely as some to accumulate lots of entries, especially since it will only hold the cameras that remain across worlds.
And yes, the calling code offers no better place to cache these values, so…
Uh…
This is fine.
Nothing to change.

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/sceneeditor/StorytellingSceneEditor.java
> +    topTransform.translation.y = targetTranslation.y + (targetHeight != 0 ? clampCameraValue(targetHeight * DEFAULT_LAYOUT_CAMERA_Y_OFFSET) : DEFAULT_LAYOUT_CAMERA_Y_OFFSET);
Should this use DEFAULT_TOP_CAMERA_Y_OFFSET?

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/sceneeditor/StorytellingSceneEditor.java
> +    // Translation helps clip things that might be over our object, based on how large it is. (It doesn't always succeed)
This makes me wonder if we could ameliorate the issue by adjusting the near clipping plane based on the size of the model.
A thought for discussion and possibly the future, not to address in this PR.

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/resources/org/alice/ide/croquet/models/ast/croquet.properties
> +CenterCameraOnOperation = Center in Camera View
Keys should be in alpha order. It makes comparisons easier, and helps with import/export.

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/resources/org/alice/ide/croquet/models/ast/croquet_en_CA.properties
> +CenterCameraOnOperation = |Center in Camera View|
Alpha order here too.

2023-05-01 17:05 UTC, dabeshouse commented on core/util/src/main/java/edu/cmu/cs/dennisc/math/AxisAlignedBox.java
> +    String debugString = AxisAlignedBox.class.getName() +
I like the added detail.
Unfortunately, this code breaks the Alice checkstyle.
When changing for that it could change to formatted() or a StringBuilder.
Why did you introduce the debugString variable?

2023-05-01 17:05 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/oneshot/OneShotUtilities.java
> +        if (!field.getValueType().isAssignableTo(SCamera.class) &&
Alice checkstyle is grumpy about these lines.
Feel free to curse my name as you change them.

2023-05-02 18:42 UTC, jennej commented on core/ide/src/main/java/org/alice/stageide/sceneeditor/StorytellingSceneEditor.java
> +    topTransform.translation.y = targetTranslation.y + (targetHeight != 0 ? clampCameraValue(targetHeight * DEFAULT_LAYOUT_CAMERA_Y_OFFSET) : DEFAULT_LAYOUT_CAMERA_Y_OFFSET);
oh, good catch.

2023-05-03 14:20 UTC, dabeshouse approved these changes

2023-05-03 14:20 UTC, merged