Feature/add vr user
TheAliceProject/alice3 pull request #324
Opened 2023-06-02 14:45 UTC by dabeshouse

Adds code for VR camera worlds and refactors existing code but no change yet to behavior.

2023-06-07 00:04 UTC, jennej requested changes
looks like some commented code snuck into the merge, so remove those for sure.

i can probably be convinced on getMovableParent but I'm not quite there.

2023-06-07 00:04 UTC, jennej commented on core/story-api/src/main/java/org/lgna/story/SVRHeadset.java
> +
nitpicky- but up til here the functions were in order set/get and here you switch to get/set

2023-06-07 00:04 UTC, jennej commented on core/story-api/src/main/java/org/lgna/story/SVRUser.java
> +/**
i like how you're blaming dennis for this new class ;)

2023-06-07 00:04 UTC, jennej commented on core/scenegraph/src/main/java/edu/cmu/cs/dennisc/scenegraph/AbstractCamera.java
> +
Are there instances left where we still need to call the old getParent? (What's the benefit here of a new function vs overriding? )

2023-06-07 00:04 UTC, jennej commented on core/scenegraph/src/main/java/edu/cmu/cs/dennisc/scenegraph/AbstractCamera.java
> +
(i'm worried because now we need to rely on people knowing not to call getParent and we're not good at knowing.)

2023-06-07 00:04 UTC, jennej commented on core/ide/src/main/java/org/alice/stageide/oneshot/OneShotUtilities.java
>        //      if( field.getValueType().isAssignableTo( SBiped.class ) && ( field.getValueType() instanceof NamedUserType ) ) {
i noticed that you didn't exclude the SVRUser from my new menu item, and I've been thinking about it and should we not be excluding the camera either? I feel like we probably want to do the same thing for the SCamera for centering...

2023-06-07 00:04 UTC, jennej commented on alice-ide/src/main/resources/org/alice/stageide/apis/org/lgna/story/classinfos.json
> +      {
should these be alphabetized? now you have set, gets, and then sets :P

2023-06-07 00:04 UTC, jennej commented on core/ide/src/main/java/org/alice/stageide/sceneeditor/viewmanager/CameraMarkerTracker.java
> +    if (trackedMarker != null) {
you can remove these comments

2023-06-07 15:21 UTC, dabeshouse commented on core/story-api/src/main/java/org/lgna/story/SVRHeadset.java
> +
A fair pick. Reordered.

2023-06-07 15:22 UTC, dabeshouse commented on core/story-api/src/main/java/org/lgna/story/SVRUser.java
> +/**
Oops. Removed.

2023-06-07 15:33 UTC, dabeshouse commented on core/scenegraph/src/main/java/edu/cmu/cs/dennisc/scenegraph/AbstractCamera.java
> +
There are still many callers of `Component.getParent()` (Including this method), but I added a comment.

2023-06-07 15:38 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/oneshot/OneShotUtilities.java
>        //      if( field.getValueType().isAssignableTo( SBiped.class ) && ( field.getValueType() instanceof NamedUserType ) ) {
I merged in your code without fully considering it. I have added the SVRUser exclusion below.

2023-06-07 15:43 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/sceneeditor/viewmanager/CameraMarkerTracker.java
> +    if (trackedMarker != null) {
Yes I can. Oops

2023-06-07 15:45 UTC, dabeshouse commented on alice-ide/src/main/resources/org/alice/stageide/apis/org/lgna/story/classinfos.json
> +      {
It feels like it could lead to a lot of raveling.
This file could have ordering, but I am too indecisive to impose it even in the small.

2023-06-08 19:27 UTC, jennej commented on core/scenegraph/src/main/java/edu/cmu/cs/dennisc/scenegraph/AbstractCamera.java
> +
oh, i was suggesting changing getParent on the AbstractCamera class, not changing anything about Component.getParent

2023-06-08 20:51 UTC, dabeshouse commented on core/scenegraph/src/main/java/edu/cmu/cs/dennisc/scenegraph/AbstractCamera.java
> +
I am still not sure what you are suggesting.
AbstractCamera inherits getParent() from Component, so if I overrode it the semantics would change for AbstractCamera, but only when it is a headset. I would worry about that affecting the more general purpose users of getParent().

2023-06-09 19:03 UTC, dabeshouse commented
I pulled out the commented out code from the merge. The use of parent and movableParent remains and can be discussed further.

2023-06-09 19:03 UTC, merged