Display recently used custom values in the custom decimal number menu
TheAliceProject/alice3 pull request #415
Opened 2024-09-10 03:46 UTC by dportnoy15

2024-09-17 17:52 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/RecentExpressionFillerInner.java
> +        if (!literals.contains(value)) {
This checks against the current list of literals, which may not be the same the next time.

If you look at IntegerValueDetails and NumberValueDetails you can see the variations.
Those classes also have minimum and maximum values, which should be applied to filter the custom values.

Perhaps the recent values should be longer than the quantity that might be displayed and only filtered when creating the list.

2024-09-17 17:52 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/RecentExpressionFillerInner.java
> +public abstract class RecentExpressionFillerInner<T> extends ExpressionFillerInner {
Abstraction! Unification! Good things here.

2024-09-17 17:52 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/RecentExpressionFillerInner.java
> + * Copyright (c) 2006, 2015, Carnegie Mellon University. All rights reserved.
Change to 2024?

2024-09-18 17:14 UTC, jennej commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/RecentExpressionFillerInner.java
> +
do we ever anticipate needing to call this function separately? i'm not convinced that it shouldn't just be a part of addRecentValue

2024-09-18 17:14 UTC, jennej commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/RecentExpressionFillerInner.java
> +        // the value will be null if the user either picked an existing value from the dropdown, or picked to enter a custom value, but then canceled
thank you for your comments

2024-10-10 17:45 UTC, dabeshouse requested changes
Looks good.
There is a checkstyle issue to address, and a few even less significant comments.

2024-10-10 17:45 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/IntegerFillerInner.java
> +    ExpressionWithRecentValuesCreatorComposite creatorComposite = IntegerCustomExpressionCreatorComposite.getInstance();
Since you set this variable, you could use it below on line 103.

2024-10-10 17:45 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/cascade/fillerinners/StringFillerInner.java
> +    ExpressionWithRecentValuesCreatorComposite creatorComposite = StringCustomExpressionCreatorComposite.getInstance();
Like the Integer case above, this could be used on line 73.

2024-10-10 17:45 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/custom/DoubleCustomExpressionCreatorComposite.java
> +    return ((DoubleLiteral) getValue()).value.getValue();
Seeing this pattern repeated in each class makes me sad, but without reworking the generics in `CustomExpressionCreatorComposite` I guess this is what we have (and fulfills my earlier request).

2024-10-10 17:45 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/stageide/StoryApiConfigurationManager.java
> -  @Override
My own robot enforced pedantry, but this method removal left unused imports above.
Please remove them to make checkstyle happy.

2024-10-10 17:45 UTC, dabeshouse commented on core/ide/src/main/java/org/alice/ide/custom/ExpressionWithRecentValuesCreatorComposite.java
> +        // and reverse the list to show most revent values last
sp "recent"

2024-10-15 20:09 UTC, dabeshouse approved these changes

2024-10-15 20:09 UTC, merged